---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  ansible_verbose: true
  ansible_verbosity: 2
  require_ruby_for_busser: false
  require_chef_for_busser: true
  hosts: all

platforms:
  - name: ubuntu-14.04
  - name: centos-6.7
    driver_config:
      box: wittman/centos-6.7-ansible
  - name: centos-7.2
    driver_config:
      box: wittman/centos-7.2-ansible
  - name: ubuntu-16.04

suites:
  - name: default
  - name: logfile
  - name: sentinel
  - name: checksum
  - name: service-name
