- name: set redis to slave automatically
  set_fact:
    redis_slaveof: >-
      {{ ansible_local[redis_service_name].master_host }}
      {{ ansible_local[redis_service_name].master_port }}
  when: >
    ansible_local[redis_service_name].role|default() == 'slave'

- name: set redis to master automatically
  set_fact:
    redis_slaveof: ~
  when: >
    ansible_local[redis_service_name].role|default() == 'master'
