---
- name: Server - create redis working directory
  file:
    path: "{{ redis_dir }}"
    state: directory
    recurse: yes
    owner: "{{ redis_user }}"

- name: Server - create redis init script
  template:
    src: "{{ item }}"
    dest: /etc/init.d/{{ redis_service_name }}
    mode: 0755
  # Choose the distro-specific template. We must specify the templates
  # path here because with_first_found tries to find files in files/
  with_first_found:
    - files:
      - "{{ ansible_os_family }}/redis.init.j2"
      - default/redis.init.j2
      paths:
        - ../templates
  when: redis_as_service and ansible_service_mgr|default() != "systemd"

- name: Server - create redis systemd service
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ redis_service_name }}.service
    mode: 0644
  with_first_found:
    - files:
      - "{{ ansible_os_family }}/redis.service.j2"
      - default/redis.service.j2
      paths:
        - ../templates
  register: redis_unit_file
  when: redis_as_service and ansible_service_mgr|default() == "systemd"

- name: Server - create systemd tmpfiles configuration
  template:
    src: etc/tmpfiles.d/redis.conf.j2
    dest: /etc/tmpfiles.d/redis.conf
    mode: 0644
  when:
    - redis_as_service
    - ansible_service_mgr|default() == 'systemd'

- name: Server - reload systemd daemon
  systemd:
    daemon_reload: true
  when:
    - redis_as_service
    - ansible_service_mgr|default() == "systemd"
    - redis_unit_file is changed

- name: Server - set redis to start at boot
  service:
    name: "{{ redis_service_name }}"
    enabled: yes
  when: redis_as_service

# Check then create log dir to prevent aggressively overwriting permissions
- name: Server - check if log directory exists
  stat:
    path: "{{ redis_logfile|dirname }}"
  register: logdir
  changed_when: false
  when: redis_logfile != '""'

- name: Server - create log directory if it does not exist
  file:
    state: directory
    path: "{{ redis_logfile|dirname }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  when:
    - redis_logfile != '""'
    - not logdir.stat.exists

# Create an empty log file only if destination file does not exist
- name: Server - create the log file
  copy:
    content: ""
    dest: "{{ redis_logfile }}"
    force: no
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  when: redis_logfile != '""'

- name: Server - check if pid directory exists
  stat:
    path: "{{ redis_pidfile|dirname }}"
  register: piddir
  changed_when: false
  when: redis_pidfile != '""' and ansible_service_mgr|default() != "systemd"

- name: Server - create pid directory if it does not exist
  file:
    state: directory
    path: "{{ redis_pidfile|dirname }}"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  when:
    - redis_pidfile != '""'
    - ansible_service_mgr|default() != "systemd"
    - not piddir.stat.exists

# A "reference" config file is created, that will not be re-written by redis.
# This file is used by Ansible to check for configuration changes (and trigger
# service restart).
- name: Server - create redis reference config file
  template:
    src: redis.conf.j2
    dest: /etc/redis/{{ redis_config_file_name }}.reference
    owner: "{{ redis_user }}"
    mode: 0640
  register: redis_refconf
  notify: "restart redis {{ redis_port }}"

# Create the "real" redis config file: the one that will be re-written by redis.
- name: Server - enforce new redis config file
  copy:
    remote_src: yes
    src: /etc/redis/{{ redis_config_file_name }}.reference
    dest: /etc/redis/{{ redis_config_file_name }}
    owner: "{{ redis_user }}"
    mode: 0640
  when: redis_refconf.changed

- name: Server - add redis init config file (RedHat)
  template:
    dest: /etc/sysconfig/{{ redis_service_name }}
    src: redis.init.conf.j2
    mode: 0600
  when: ansible_os_family == "RedHat"
  notify: "restart redis {{ redis_port }}"

- name: Server - add redis init config file (Debian)
  template:
    dest: /etc/default/{{ redis_service_name }}
    src: redis.init.conf.j2
    mode: 0600
  when: ansible_os_family == "Debian"
  notify: "restart redis {{ redis_port }}"

- name: Server - ensure redis is running
  service:
    name: "{{ redis_service_name }}"
    state: started
  when: redis_as_service
