---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

    - set_fact:
        redis_bind: 127.0.0.1
        redis_port: 6379
        # redis_verify_checksum: true
        redis_logfile: "/var/log/redis/redis_{{ redis_port }}.log"
        redis_syslog_enabled: "no"


      tags:
        - prereqs

  roles:
    - role: ansible-redis
      tags:
        - redis
